node_table = struct2table(struct(...
    "Name",     ["1"; "2"; "3"]...
  )...
);
edge_table = struct2table(struct(...
    "EndNodes",          [1, 1; 1, 2; 1, 2; 1, 2; 1, 2; 1, 2; 2, 1; 3, 1] ...
  ) ...
);

graph = digraph(edge_table, node_table)
graph.Edges
plot(graph)