% mystruct = struct(...
%               "Name",     [1; 2],...
%               "Object",   [ConvexPolyhedron.fromLine([0; 1], [1; 0]); [0; 1]]...
%             )

% struct2table(mystruct)

cp = ConicalPartition.fromNumSlices(5);
TransitionGainDigraph(cp)


% struct2table(struct(...
%               "Name",     arrayfun(@vertexIndex2Name,     conical_partition.vertex_indices'),...
%               "TeXLabel", arrayfun(@vertexIndex2TexLabel, conical_partition.vertex_indices'),...
%               "Index",    conical_partition.vertex_indices',...
%               "x",        conical_partition.vertices(1, :)',...
%               "y",        conical_partition.vertices(2, :)'...
%             ));