"""
This type stub file was generated by pyright.
"""

"""Interface to linear programming solvers.

The `polytope` package selects the default solver as follows:

1. use GLPK if installed
2. otherwise use SciPy

You can change this default at runtime by setting the variable
`default_solver` in the module `solvers`.

For example:

```python
from polytope import solvers

solvers.default_solver = 'scipy'

# to inspect which solvers were successfully imported:
print(solvers.installed_solvers)
```

Choose an installed solver to avoid errors.
"""
logger = ...
installed_solvers = ...
if 'glpk' in installed_solvers:
    default_solver = ...
else:
    default_solver = ...
def lpsolve(c, G, h, solver=...): # -> dict[Any, Any] | dict[str, Any]:
    """Try to solve linear program with given or default solver.

    Solvers:
        - `cvxopt.glpk`: identified by `'glpk'`
        - `scipy.optimize.linprog`: identified by `'scipy'`
        - MOSEK: identified by `'mosek'`

    @param solver:
        - `in {'glpk', 'mosek', 'scipy'}`
        - `None`: use the module's `default_solver`

        You can change the default choice of solver by setting
        the module variable `default_solver`. See the module's
        docstring for an example.

    @return: solution with status as in `scipy.optimize.linprog`
    @rtype: `dict(status=int, x=argmin, fun=min_value)`
    """
    ...

